server:  port: 8099
spring:
  datasource:
    url: jdbc:mysql://devdsm-java-db.cwzf6ionsw6p.ap-south-1.rds.amazonaws.com:3306/DEVINTUITSHIPSUMMS    
    username: devumms2018
    password: devintuitships-ummstotw0o
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect