spring:
  datasource:
    url: jdbc:mysql://testintuitshipsumms022320.cuwqhuxmvzzy.ap-south-1.rds.amazonaws.com:3306/Test_Intuitships_UMMS    
    username: testumms2018
    password: TstIntuitshipstwenty2O
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect